
server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  dashboard:
    path: /eureka-web-ui
  server:
    enable-self-preservation: true
  client:
    healthcheck:
      enabled: true


---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/



#---
#spring:
#  profiles: peer2
#
#server:
#  port: 8762
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#
#
#---
#spring:
#  profiles: rancher-peer1
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-peer2:8760/eureka/
#
#---
#spring:
#  profiles: rancher-peer2
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-peer1:8760/eureka/

